export const APP_NAME = 'StreetPlay';
export const MAIN_APP_TITLE = 'Welcome to React';
export const MAIN_APP_DESCRIPTION = 'Выбирай приложение в меню для запуска';
export const HINT_CHARACTER_SEARCH = 'Поиск персонажа';
export const BUTTON_CHARACTER_LOAD = 'Загрузить персонажей из SW';
export const DATA_URL = 'https://swapi.co/api/people/?format=json';
export const LOGIN_DIALOG_TITLE = 'Вход на сайт';
export const LOGIN_DIALOG_TEXT_FIELD_LOGIN_HINT = 'Логин или электропочта';
export const LOGIN_DIALOG_TEXT_FIELD_LOGIN_LABEL = 'Введите логин или электропочту';
export const LOGIN_DIALOG_TEXT_FIELD_PASSWORD_HINT = 'Пароль';
export const LOGIN_DIALOG_TEXT_FIELD_PASSWORD_LABEL = 'Введите пароль';
export const LOGIN_DIALOG_LINK_LABEL = 'Зарегистрироваться';
